Warning Cleanups
apple/swift-lldb pull request #1003
Opened 2018-10-25 23:10 UTC by compnerd

This is intended to cleanup most of the warnings from the LLDB build.  The ones in particular that are left are related to C11 and four character codes.

2018-10-25 23:14 UTC, compnerd commented
CC: @dcci @adrian-prantl @fredriss

2018-10-26 00:16 UTC, jimingham requested changes
It seems like this patch has a bunch of changes against files that exist on llvm.org, and in code that is not swift specific - so should apply there.  Any change that touches code shared between llvm.org and github should be made on llvm.org, and then the llvm.org -> github/upstream-with-swift automerger will pick it up.

Can you either ensure that the code in shared files is in code only present on github (there shouldn't be much of that anymore) or push it to llvm.org first and then merge it over.  We really want to minimize the divergence between upstream-with-swift on github and llvm.org.

2018-10-26 00:57 UTC, compnerd commented
Sure, I can upstream the changes to the files that exist there already and let it come through overnight through the automerger.

2018-10-26 01:22 UTC, dcci approved these changes
Yes, please upstream the changes first, then back port here and update the remaining files.
Other than that, it looks good.

2018-10-26 02:17 UTC, compnerd commented
@jimingham, @dcci - I just had a look, the change that can be upstreamed is close to zero: there is one switch statement that can be upstreamed.  The other changes are all local only.  They are due to the local changes that have been made to lldb and the extensions due to swift.

2018-10-26 17:47 UTC, dcci commented
OK, well, I guess you're almost fine then. Upstream that little bit and then apply all the changes here.
I think we should keep the divergence as little as possible.

2018-10-26 18:12 UTC, merged

2018-10-26 18:29 UTC, dcci commented
For the future, I think this is not the flow that we use.
We generally merge to stable, not `upstream-with-swift.` Also, we first do the llvm.org upstream commit and then cherry pick here. You may do the other way around now, but something to keep in mind for the future.