Fix file_idx type to uint16_t from 11 bits.
apple/swift-lldb pull request #1177
Opened 2018-12-24 09:48 UTC by frozenrainyoo

file_idx type is NOT uint16_t, provide 11 bits.

if file_idx is 2691
file_idx = 2691 (0b101010000011) <-- 12bits

file_idx provides 11 bits.
so, file_idx variable changed from 2691(0b101010000011) to 643(0b01010000011).

https://bugs.llvm.org/show_bug.cgi?id=39816

2019-01-02 20:46 UTC, adrian-prantl commented
Thanks for the patch. This should go into lldb on llvm.org first and then should be cherry-picked here if need be.

2019-01-02 21:25 UTC, adrian-prantl requested changes
We need to land this upstream first and then cherry-pick it to swift-5.0-branch. The stable branch will get it automatically the next time we rebranch from upstream-with-swift.

2019-01-02 21:26 UTC, adrian-prantl commented
I created https://reviews.llvm.org/D56218 for the upstream patch.

2019-01-03 05:15 UTC, frozenrainyoo commented
Thank you.
I will check this bug in next version.
we have being use custom lldb. T T

2019-01-03 05:15 UTC, closed without merging