[Swift] Rewrite the SIMD vector formatter.
apple/swift-lldb pull request #1298
Opened 2019-02-14 20:35 UTC by dcci

The representation changed.

<rdar://problem/46330565>

2019-02-14 20:35 UTC, dcci commented
@stephentyrone I'm adding tests for the new representation/testing/cleaning maybe this up a bit, but I would appreciate if you can give an early look so there's some chance we're going to merge this today.

2019-02-14 20:41 UTC, vedantk commented on source/Plugins/Language/Swift/SwiftFormatters.cpp
> +  stream.Printf("(");
Any chance the PrintRow helper could be reused here?

2019-02-14 20:48 UTC, stephentyrone commented
This all looks reasonable to me.

2019-02-14 21:06 UTC, jimingham requested changes
Two small fixes.  Other than that, it looks good.

2019-02-14 21:06 UTC, jimingham commented on source/Plugins/Language/Swift/SwiftFormatters.cpp
> +  lldbassert(generic_args.size() == 1 && "broken SIMD type");
You should also return false here.  Otherwise you'll go on trying to take apart a broken type.

2019-02-14 21:06 UTC, jimingham commented on source/Plugins/Language/Swift/SwiftLanguage.cpp
> +  const char *newSIMDTypes = "^SIMD[0-9]+<.*>";
I don't think anything is allowed after the <TYPE> so you should have <.*>$

2019-02-14 22:58 UTC, dcci commented
I addressed all the comments.

2019-02-14 22:59 UTC, dcci commented
@swift-ci test and merge

2019-02-14 22:59 UTC, vedantk commented
lgtm

2019-02-14 23:03 UTC, stephentyrone approved these changes

2019-02-15 00:00 UTC, jimingham approved these changes
LGTM

2019-02-15 00:08 UTC, merged