Upstream rpath-related test changes for Swift-in-Apple-OSs
apple/swift-lldb pull request #1588
Opened 2019-05-16 04:10 UTC by jrose-apple

Cherry-pick a bunch of changes that deal with the Swift stdlib and overlays living in /usr/lib/swift/, mostly from @adrian-prantl. These changes shipped in Apple Swift 5.0 but never made it back to open source. LLDB side of apple/swift#24787.

(not urgent at this point because we're so late with it)

rdar://problem/50748941

2019-05-16 04:10 UTC, jrose-apple commented
apple/swift#24787
@swift-ci test

2019-05-16 04:51 UTC, JDevlieghere approved these changes

2019-05-16 16:12 UTC, jrose-apple commented
\*grumble\* Maybe I missed a cherry-pick, or maybe these tests have been added since.

2019-05-16 18:07 UTC, dcci requested changes
Jordan, there's at least one cherry-pick that's missing, we need to pick the changes to make the SwiftREPL lit tests working (it's a change in lit.cfg). If you can't find it, let me know.

2019-05-17 20:25 UTC, dcci approved these changes
LGTM now, thanks. I'll look at the cmake changes to see if they're required and upstream in a later commit. Thank you!

2019-05-17 20:26 UTC, jrose-apple commented
apple/swift#24787
@swift-ci test

2019-05-17 20:42 UTC, jrose-apple commented
apple/swift#24787
@swift-ci test

2019-05-18 01:02 UTC, jrose-apple commented
Waiting to merge until a time when I can manually resolve the conflicts that will immediately happen in the Apple-internal branches I cherry-picked these from.

2019-08-01 22:10 UTC, jrose-apple commented
apple/swift#24787
@swift-ci test

2019-08-01 22:41 UTC, jrose-apple commented
apple/swift#24787
@swift-ci test

2019-08-02 00:18 UTC, jrose-apple commented
Ugh, I see what I did wrong.

apple/swift#24787
@swift-ci test

2019-08-02 00:34 UTC, adrian-prantl commented on packages/Python/lldbsuite/test/lang/swift/clangimporter/config_macros/Makefile
> +	  -toolchain-stdlib-rpath
I should update these to use the default rules and just modify LD_EXTRAS...

2019-08-02 00:34 UTC, adrian-prantl commented
Thanks!

2019-08-02 01:09 UTC, jrose-apple commented
> Waiting to merge until a time when I can manually resolve the conflicts that will immediately happen in the Apple-internal branches I cherry-picked these from.

Still relevant! I'll do this tomorrow if the compiler side passes all its tests.

2019-08-02 21:40 UTC, merged