Swift 4.0 branch with exclusivity suppression
apple/swift-lldb pull request #201
Opened 2017-05-11 22:18 UTC by lhames

Explanation:

These two commits teach LLDB to temporarily suppress enforcement of exclusivity during evaluation of swift expressions. This is necessary to allow debugger expressions to access variables that are exclusively owned in the original program in the context where the expression is to be evaluated.

Scope: Affects evaluation of swift expressions in LLDB. Will disable exclusivity enforcement by the swift runtime while each expression is executed, then re-enable it afterwards. This will suppress exclusivity errors in expressions, but should not affect expression evaluation otherwise.  

Radar (and possibly SR Issue): <rdar://problem/31715465>

Risk: Affects evaluation of swift expressions under LLDB only. Low risk.

Testing: Some testing by hand, plus test cases for:
(1) a single expression accessing an exclusively owned variable, and
(2) two nested expressions accessing an exclusively owned variable

2017-05-11 22:21 UTC, lhames commented
@swift-ci please test

2017-05-12 00:57 UTC, jimingham requested changes
The overall structure is fine.  See the detailed comments below.

2017-05-12 00:57 UTC, jimingham commented on packages/Python/lldbsuite/test/lang/swift/expression/exclusivity_suppression/TestExclusivitySuppression.py
> +
I don't think you finished this test.   It's pretty much identical to the first test (except for setting a second breakpoint.)

2017-05-12 00:57 UTC, jimingham commented on packages/Python/lldbsuite/test/lang/swift/expression/exclusivity_suppression/TestExclusivitySuppression.py
> +
Ditto for this test.

2017-05-12 00:57 UTC, jimingham commented on packages/Python/lldbsuite/test/lang/swift/expression/exclusivity_suppression/TestExclusivitySuppression.py
> +
We now have 10 cut and paste copies of this function around.  We should move it to lldbutil.py and use it from there.

2017-05-12 00:57 UTC, jimingham commented on source/Plugins/ExpressionParser/Swift/SwiftUserExpression.cpp
> +  if (auto process = m_jit_process_wp.lock())
It should be fine to assert if no process here.  You can run lldb's expression parser in "calculator" mode without a process.  But you can only do that if the expression is IR interpretable.  This code only gets run once we decide we can't IR interpret the expression and are actually going to run it.  For that you have to have a process.

You might be debugging a C program, and somebody tries to run a Swift expression.  There is no swift loaded into your program so no swift language runtime.  The lookup is going to fail, and cache that there's no swift language runtime.  Then you load some library that has swift code.  If retry_if_null is true (the default) we will look for it again - finding it this time.  I actually can't think of a good reason to set this to false off the top of my head.

As above, the runtime can come back as null, so it's probably good to check here.  I can't see how you would be able to get to here without finding a language runtime however, so again it might be appropriate to assert.

2017-05-12 00:57 UTC, jimingham commented on source/Target/SwiftLanguageRuntime.cpp
> +                    "disableExclusivityChecking flag state");
Add the error's message to the log message (error.GetCString() will get it for you).

2017-05-12 00:57 UTC, jimingham commented on source/Target/SwiftLanguageRuntime.cpp
> +                      "disableExclusivityChecking flag state");
Same here, put the error's message into the log output.

2017-05-12 00:57 UTC, jimingham commented on source/Target/SwiftLanguageRuntime.cpp
> +      target, g_disableExclusivityChecking, eSymbolTypeData);
That API (FindSymbolForSwiftObject) makes me sad.  It does nothing swift specific at all, it just looks up a symbol by name globally.  So no way does it belong in SwiftLanguageRuntime (probably Target instead).  And it doesn't actually return the symbol, it finds the symbol's address.

This function is really the same as the first half of:

Target::FindLoadAddrForNameInSymbolsAndPersistentVariables

Probably better to break that into Target::FindLoadAddrForNameInSymbols and Target::FindLoadAddrForNameInSymbolsAndPersistentVariables.  Then you can use the former for your purposes.

2017-05-12 00:57 UTC, jimingham commented on source/Target/SwiftLanguageRuntime.cpp
> +      if (bytes_written != sizeof(m_original_dynamic_exclusivity_flag_state)) {
Same comment as when reading.  You need to get the sizeof(bool) as above.  Then you should make a Scalar with the value of 1 (scalars don't know about bools, but a C++ bool true is an int with value 1) and you can use WriteScalarToMemory to get the byte swapping right.

2017-05-12 00:57 UTC, jimingham commented on source/Target/SwiftLanguageRuntime.cpp
> +                              error);
You are assuming that the size of a Host bool and the size of a Target bool are the same here.  That's not guaranteed to be true.  You can get the TypeSystem from the Target (GetScratchTypeSystemForLanguage is good, that's the expression context.) then get call GetBuiltinTypeByName("bool") then get the size from the type you got back.

2017-05-12 00:57 UTC, jimingham commented on source/Target/SwiftLanguageRuntime.cpp
> +                    "disableExclusivityChecking flag state");
Again, add the error string here.

2017-05-12 17:01 UTC, lhames commented on packages/Python/lldbsuite/test/lang/swift/expression/exclusivity_suppression/TestExclusivitySuppression.py
> +
Oops - this was meant to be left out of this commit and added in a follow-up.

I have a "complete" version of this test but it fails due to unexpected behavior in SBProcess::continue - I'll see if I can get that sorted out along with the other issues you've flaged and post the full test.

2017-05-12 17:01 UTC, lhames commented on packages/Python/lldbsuite/test/lang/swift/expression/exclusivity_suppression/TestExclusivitySuppression.py
> +
Ditto here.

2017-05-12 17:02 UTC, lhames commented on packages/Python/lldbsuite/test/lang/swift/expression/exclusivity_suppression/TestExclusivitySuppression.py
> +
Sounds good to me. Is that something that would be better done in a separate commit though?

2017-05-12 17:05 UTC, lhames commented on source/Plugins/ExpressionParser/Swift/SwiftUserExpression.cpp
> +  if (auto process = m_jit_process_wp.lock())
Ok. I'll add the appropriate asserts and remove those comments.

2017-05-12 17:06 UTC, lhames commented on source/Target/SwiftLanguageRuntime.cpp
> +      target, g_disableExclusivityChecking, eSymbolTypeData);
Ok. I'll file a bug to refactor this in a follow-up.

2017-05-12 17:09 UTC, lhames commented on source/Target/SwiftLanguageRuntime.cpp
> +                              error);
Sounds good. I'll add the bool size query (and log error messages suggested below).

2017-05-12 18:18 UTC, lhames commented on source/Target/SwiftLanguageRuntime.cpp
> +                              error);
Is the type system returned by GetScratchTypeSystemForLanguage going to be C++ or Swift? We need the C++ type size here (though I suspect they're the same in practice).

2017-05-12 18:20 UTC, lhames commented on source/Target/SwiftLanguageRuntime.cpp
> +                              error);
Oh - the language is an argument to GetScratchTypeSystemForLanguage. Ignore that then. :)

2017-05-12 23:48 UTC, lhames commented
@swift-ci please test

2017-05-15 22:51 UTC, jimingham reviewed
I don't see the SwiftLangaugeRuntime.cpp changes in the latest diff here.

2017-05-15 22:51 UTC, jimingham commented on include/lldb/Target/SwiftLanguageRuntime.h
> +
Be nice to have a comment describing what these are for.

2017-05-15 22:51 UTC, jimingham commented on packages/Python/lldbsuite/test/lang/swift/expression/exclusivity_suppression/TestExclusivitySuppression.py
> +
Yes, that's fine.

2017-05-15 22:51 UTC, jimingham commented on source/Plugins/ExpressionParser/Swift/SwiftUserExpression.cpp
> +  // Can the runtime ever come back as null?
You don't need this comment any more, do you?

2017-05-15 22:55 UTC, jimingham commented on source/Plugins/ExpressionParser/Swift/SwiftUserExpression.cpp
> +    llvm_unreachable("Can't execute an expression without a process");
An expression could cause a process to exit.  So while you can't START an expression executing without a process, it is possible that it not exist when you exit.  I am pretty sure you won't get called to here in that case, but it's probably best to just give up quietly on the way out if you don't have a process.

2017-05-15 22:58 UTC, jimingham reviewed
Ah, okay, I found the SwiftLanguageRuntime.cpp changes by going to the latest hash directly.  That part of the diff looks fine.

2017-05-15 23:58 UTC, lhames commented
@swift-ci please test

2017-05-16 16:58 UTC, jimingham commented
That looks fine.  Please remember to do the cleanups to the FindSymbolForSwiftObject and check_expression in subsequent commits.

2017-05-16 16:58 UTC, jimingham approved these changes

2017-05-16 19:19 UTC, merged