Tests: make ClangImporter tests compatible with cross-compilation and remote testing
apple/swift-lldb pull request #2028
Opened 2019-10-02 18:30 UTC by fredriss

Those tests have 2 kinds of issues:
 - Some Makefiles were too adhoc. Modernize them to use the Makefile.rules support.
 - Shared libraries need to be registered to be transfered to the remote platform during testing.

2019-10-02 18:30 UTC, fredriss commented
@swift-ci test

2019-10-02 19:25 UTC, fredriss commented
@swift-ci test

2019-10-02 19:27 UTC, adrian-prantl commented on packages/Python/lldbsuite/test/lang/swift/clangimporter/config_macros/Makefile
> +		VPATH=$(SRCDIR) -I $(SRCDIR) -f $(SRCDIR)/Makefile.dylib all
nice!

2019-10-02 20:00 UTC, dcci approved these changes

2019-10-02 20:03 UTC, fredriss commented on packages/Python/lldbsuite/test/lang/swift/clangimporter/config_macros/Makefile.dylib
> +SWIFTFLAGS_EXTRA = -Xcc -DDEBUG=1 -Xcc -D -Xcc SPACE -Xcc -U -Xcc NDEBUG
This should be SWIFTFLAGS_EXTRA*S*

@adrian-prantl I suppose this makes the test wrong?

2019-10-02 20:09 UTC, adrian-prantl requested changes

2019-10-02 20:09 UTC, adrian-prantl commented on packages/Python/lldbsuite/test/lang/swift/clangimporter/config_macros/Makefile
> +SWIFT_SOURCES = main.swift
:=

2019-10-02 20:09 UTC, adrian-prantl commented on packages/Python/lldbsuite/test/lang/swift/clangimporter/config_macros/Makefile
> +SWIFTFLAGS_EXTRAS = -Xcc -DDEBUG=1 -Xcc -DSPACE -Xcc -UNDEBUG -I. -L. -lDylib
:= (these are just for consistency)

2019-10-02 20:09 UTC, adrian-prantl commented on packages/Python/lldbsuite/test/lang/swift/clangimporter/config_macros/Makefile.dylib
> +LEVEL = ../../../../make
most tests call this file `dylib.mk`. We generally use .mk as a suffix for sub-makefiles (though they aren't technically makefile fragments, but proper standalone recursive files).

2019-10-02 20:09 UTC, adrian-prantl commented on packages/Python/lldbsuite/test/lang/swift/clangimporter/config_macros/Makefile.dylib
> +DYLIB_NAME = Dylib
:=

2019-10-02 20:09 UTC, adrian-prantl commented on packages/Python/lldbsuite/test/lang/swift/clangimporter/objcmain_conflicting_dylibs_failing_import/Makefile
> +OBJC_SOURCES = main.m
That actually makes more sense than what we had originally!

2019-10-02 20:09 UTC, adrian-prantl commented on packages/Python/lldbsuite/test/lang/swift/clangimporter/objcmain_conflicting_dylibs_failing_import/Makefile
> +LD_EXTRAS = -lFoo -lBar -L$(shell pwd)
= can stay but `-L$(BUILDDIR)` is nicer

2019-10-02 20:09 UTC, adrian-prantl commented on packages/Python/lldbsuite/test/lang/swift/clangimporter/objcmain_conflicting_dylibs_failing_import/Makefile
> +CFLAGS_EXTRAS = -I$(shell pwd) -fmodules
same here

2019-10-02 21:46 UTC, fredriss commented
@swift-ci test

2019-10-03 15:29 UTC, fredriss commented
@swift-ci test and merge

2019-10-03 16:20 UTC, merged