When parsing the DBGSourcePathRemapping plist entries
apple/swift-lldb pull request #249
Opened 2017-08-24 01:29 UTC by jasonmolenda

When parsing the DBGSourcePathRemapping plist entries
in a dSYM, and it's a version 2 DBGSourcePathRemapping,
in addition to the build/source paths specified, add
build/source paths with the last two filename components
removed.  This more generic remapping can sometimes
help lldb to find the correct source file in complex
projects.
<rdar://problem/33973545>

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@311622 91177308-0d34-0410-b5e6-96231b3b80d8
(cherry picked from commit 31696925e66879752f1f32cdff3f9f19bccda278)
(cherry picked from commit bdc50e2821f13e5e740c8b9670fa9d0e997d2c06)

2017-08-24 01:29 UTC, jasonmolenda commented
@swift-ci please test

2017-08-28 19:33 UTC, jimingham approved these changes
The changes themselves are fine (though the number 2 is somewhat arbitrary...)  I'm a little concerned that you had to do this in two places that look pretty similar.  You didn't add that duplication, but if it doesn't need to be there...

2017-12-13 18:04 UTC, dcci commented
@jasonmolenda Jason, are you going to merge this one?

2017-12-13 18:04 UTC, dcci commented
@swift-ci please test

2017-12-14 23:26 UTC, dcci requested changes
Actually, this needs a test before it can be merged.

2018-02-08 00:30 UTC, dcci commented
@jasonmolenda this seems to be dead, can we close it?

2018-02-09 00:55 UTC, dcci commented
Feel free to reopen this if you plan to work on it again.

2018-02-09 00:55 UTC, closed without merging