Fix Swift dictionary padding with enum keys
apple/swift-lldb pull request #259
Opened 2017-11-22 23:19 UTC by keith

When you have a dictionary which has an enum as the key such as:

```
enum Foo: String {
  case a
}

let bar = [Foo.a: 1]
```

The stride of the key is 1 byte. This differs from if you have a tuple
with the same key and value as the dictionary such as:

```
let baz = (Foo.a: 1)
```

In order to read the values from a dictionary we create a tuple which
expects 16 bytes of data (in the case the key is an enum and the value
is an int). Previously because the key was only 1 byte, we only filled
it with 9 bytes, and therefore the offsets were wrong leading to us
printing garbage data. Now instead of just using the stride of the key,
we use the stride based on the tuple type we generate for printing these
values. This works since the buffer is initialized to all 0 and
therefore acts as padding for the key.

This fixes https://bugs.swift.org/browse/SR-6290

2017-11-23 00:42 UTC, keith commented
To test this I've been using this file:

```swift
enum Enum {
    case a, b, c
}

let testA = [Enum.c: 1, Enum.b: 2]
let testB = ["a": 1, "b": 2]
let testC = (key: Enum.b, value: 2)
let testD = Set([Enum.c])
print(testA)
```

And this `lldbinit` for convenience:

```
br set -f foo.swift -l 9
br command add 1 -o "fr v testA testB testC testD"
r
```

2017-11-23 03:59 UTC, lattner commented
Great fix @keith!!

2017-11-26 05:32 UTC, DougGregor commented
@swift-ci please test

2017-11-26 23:20 UTC, keith commented
Looks like the linux failures here might be unrelated (although I'm not sure if this is the actual failure cause):

```
fatal error: error in backend: IO failure on output stream.
```

The macOS failure looks like it could be related so I'm trying to repro these locally.

2017-11-27 01:00 UTC, keith commented
The macOS tests seem to pass for me locally on my branch. It looks like based on the log this one might have failed because of a timeout:

```
[TestSwiftDictionaryNSObjectAnyObject.py FAILED] (TIMEOUT)
```

Can we run these again if that makes sense?

2017-11-27 01:37 UTC, CodaFi commented
I'll kick off the tests, but that failure looks concerning.  It seems the printer is straying pretty far outside the bounds of the object it should be reading - I would guess your local setup would have trouble reproducing this because it would appear nondeterministically.

@swift-ci please test

2017-12-06 05:51 UTC, keith commented
Anyone have thoughts on why this would fail on CI both runs, but not fail locally in my testing?

2017-12-06 06:34 UTC, keith commented
I've submitted a related PR adding tests for this case. Since they should be valuable regardless of this fix (minus the one that is disabled until this bug is fixed) I thought that made sense to be in a separate PR https://github.com/apple/swift-lldb/pull/262

2017-12-06 06:53 UTC, keith commented
Ah it looks like some of the tests that failed here were disabled in this commit https://github.com/apple/swift-lldb/commit/909ec3e70551d7c5eb40632bd5020ebb87e32f77

2017-12-06 06:54 UTC, keith commented
I've rebased on the stable branch which has these changes, so if someone could run the tests again here they should be green this time (assuming the linux OOM failures have been fixed as well)

2017-12-06 12:03 UTC, DougGregor commented
@swift-ci please test

2017-12-06 12:03 UTC, DougGregor commented
@swift-ci please test

2017-12-06 17:09 UTC, keith commented
Is this linux failure a known issue?

```
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)```

This is similar to how it has failed on Linux all 3 test runs so far

2017-12-08 20:01 UTC, dduan commented
@swift-ci please test

2017-12-08 20:37 UTC, keith commented
Looks like linux failed again for the same reason 🤔

2017-12-08 20:50 UTC, CodaFi commented
Linux failure doesn’t look infrastructure related.  @jimingham any ideas?

2017-12-13 01:48 UTC, dcci requested changes
Hi @Keith, is there any change of adding a test for this?
Also, I looked at the failure and I'm pretty confident it's unrelated. 

Can you please consider rebasing the following patch on ToT? At that point I'll spawn another build. Sorry for hanging you for so long, but it seems there are more people looking at Swift debug support in LLDB than there used to be until very recently :)

2017-12-13 01:48 UTC, dcci commented
Nvm, I just noticed you submitted another pull request for the test. My comment on rebasing still stands.

2017-12-13 15:34 UTC, keith commented
@dcci I've rebased on `stable` and added the test from https://github.com/apple/swift-lldb/pull/262 here instead.

Let me know if there's anything else I can improve here!

2017-12-13 16:04 UTC, dcci commented
Let's test this again and cross finger. If this still fails I'll take a look myself.

2017-12-13 16:04 UTC, dcci commented
@swift-ci please test

2017-12-13 17:34 UTC, dcci commented
@swift-ci please test

2017-12-13 18:25 UTC, keith commented
Looks like the Linux build failed with the same error as before

2017-12-14 15:54 UTC, dcci commented
@Keith yes, definitely not related. On a bus now but I'll check in 30 where this problem is.

2017-12-14 18:52 UTC, shahmishal commented
@swift-ci test Linux

2017-12-14 19:14 UTC, shahmishal commented
Not sure, I have not seen this before. 

```
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)
```

2017-12-14 19:17 UTC, dduan commented
It certainly _looks_ like OOM. But why would this change cause that....

2017-12-14 21:47 UTC, shahmishal commented
@swift-ci test Linux

2017-12-14 23:04 UTC, keith commented
It passed 🎉  Thanks @shahmishal !

2017-12-14 23:14 UTC, dcci commented
@shahmishal thanks. Can we get the bot back online so I can merge this?

Thanks!

--
Davide

2017-12-14 23:16 UTC, shahmishal commented
You should be able to merge now.

2017-12-14 23:21 UTC, merged

2017-12-14 23:21 UTC, dcci commented
It was an hw issue, merging this now.

2017-12-14 23:31 UTC, keith commented
Awesome! Thanks everyone for your help!