Handle Python differences on Fedora
apple/swift-lldb pull request #264
Opened 2017-12-21 15:31 UTC by tachoknight

Fedora's installation of Python gets the result of `distutils.sysconfig.get_python_lib(True,False)` as `lib64`, which causes a failure later on in the installation process as the install script is looking for the `python2.7/site-packages` directory in `lib`. This is not an issue with Ubuntu so the change tests for whether we're running on Linux, and if so and we're on Fedora, run `distutils.sysconfig.get_python_lib(False, False)` to return the same path as the rest of the Python files being built.

2017-12-21 15:41 UTC, dcci requested changes

2017-12-21 15:41 UTC, dcci commented on scripts/Python/finishSwigPythonLLDB.py
> +        if platform.system() == 'Linux':
Please move this to a separate function.

2017-12-21 15:42 UTC, dcci commented
Please rebase and squash this in a single commit.
I think this hack is alright, but I'll run the tests to make sure this doesn't break other Linux(es).
I'd wait if anybody else has opinions on this, otherwise merge
cc: @fredriss / @adrian-prantl / @jasonmolenda / @jimingham / @JDevlieghere / @vedantk

2017-12-21 15:42 UTC, dcci commented
@swift-ci please test linux

2017-12-21 20:49 UTC, tachoknight commented
Per dcci's request, I moved the code into a function and put it near the other platform-specific functions.

2017-12-22 04:17 UTC, dcci approved these changes

2017-12-22 04:17 UTC, dcci commented
Please rebase this as it contains a bunch of other unrelated changes now.
Otherwise, LGTM, and I'll merge it.

2017-12-22 05:00 UTC, dcci commented
This looks still really weird (there are 40 commits in this pull request).

2017-12-22 05:01 UTC, tachoknight commented
Yes, sorry about that, trying to fix it.

2017-12-22 05:09 UTC, tachoknight commented
Fixed with the help of the friendly folks on the #git irc channel (thank you preaction and tkazi)

2017-12-22 05:10 UTC, dcci commented
@swift-ci please test

2017-12-22 05:10 UTC, dcci commented
@tachoknight I'll merge this if it passes CI. Thanks for your contribution.

2017-12-22 05:11 UTC, dcci commented
@swift-ci please test

2017-12-22 07:37 UTC, merged