WIP: [DataFmt] Add formatters for Accelerate/simd
apple/swift-lldb pull request #652
Opened 2018-05-23 01:44 UTC by vedantk

Add Swift data formatters for vectors, matrices, and quaternions from
the Accelerate/simd framework.

rdar://40294100

2018-05-23 01:45 UTC, vedantk commented
@swift-ci test

2018-05-23 01:53 UTC, vedantk commented
@swift-ci test

2018-05-23 02:19 UTC, vedantk commented
This is WIP because in stale REPL sessions, LLDB may trigger a use-after-free bug when formatting a simd_double3 object. Here's an example:

```
$ /Users/vsk/src/github-swift-master/build/Ninja-DebugAssert/lldb-macosx-x86_64/bin/lldb -S /Users/vsk/src/github-swift-master/lldb/lit/lit-lldb-init --repl < /Users/vsk/src/github-swift-master/lldb/lit/SwiftREPL/SIMD.test | tee ~/Desktop/result.log
Welcome to Swift version 4.2-dev (LLVM c096c44a23, Clang c7422ffe24, Swift c23942012a). Type :help for assistance.
$R0: simd_int2 = (-1, 2)
$R1: simd_int3 = (-1, 2, 3)
$R2: simd_int4 = (-1, 2, 3, 4)
$R3: simd_uint2 = (1, 2)
$R4: simd_uint3 = (1, 2, 3)
$R5: simd_uint4 = (1, 2, 3, 4)
colf2: simd_float2 = (1.500000e+00, 2.000000e+00)
colf3: simd_float3 = (1.500000e+00, 2.000000e+00, 3.000000e+00)
colf4: simd_float4 = (1.500000e+00, 2.000000e+00, 3.000000e+00, 4.000000e+00)
cold2: simd_double2 = (1.500000e+00, 2.000000e+00)
cold3: simd_double3 = (3.000000e+00, 2.000000e+00, 3.000000e+00)
...

FAIL: lldb :: SwiftREPL/SIMD.test (389 of 389)
******************** TEST 'lldb :: SwiftREPL/SIMD.test' FAILED ********************
Script:
--
/Users/vsk/src/github-swift-master/build/Ninja-DebugAssert/lldb-macosx-x86_64/bin/lldb -S /Users/vsk/src/github-swift-master/lldb/lit/lit-lldb-init --repl < /Users/vsk/src/github-swift-master/lldb/lit/SwiftREPL/SIMD.test | /Users/vsk/src/github-swift-master/build/Ninja-DebugAssert/llvm-macosx-x86_64/bin/FileCheck /Users/vsk/src/github-swift-master/lldb/lit/SwiftREPL/SIMD.test
--
Exit Code: 1

Command Output (stderr):
--
/Users/vsk/src/github-swift-master/lldb/lit/SwiftREPL/SIMD.test:39:11: error: expected string not found in input
// CHECK: cold3: simd_double3 = (1.500000e+00, 2.000000e+00, 3.000000e+00)
          ^
<stdin>:12:1: note: scanning from here
cold3: simd_double3 = (3.000000e+00, 2.000000e+00, 3.000000e+00)
^

--

********************
Testing Time: 23.01s
********************
Failing Tests (1):
    lldb :: SwiftREPL/SIMD.test

  Expected Passes    : 388
  Unexpected Failures: 1
FAILED: lit/CMakeFiles/check-lldb-lit
cd /Users/vsk/src/github-swift-master/build/Ninja-DebugAssert/lldb-macosx-x86_64/lit && /usr/bin/python2.7 /Users/vsk/src/github-swift-master/build/Ninja-DebugAssert/llvm-macosx-x86_64/bin/llvm-lit --param lldb_site_config=/Users/vsk/src/github-swift-master/build/Ninja-DebugAssert/lldb-macosx-x86_64/lit/lit.site.cfg --param lldb_unit_site_config=/Users/vsk/src/github-swift-master/build/Ninja-DebugAssert/lldb-macosx-x86_64/lit/Unit/lit.site.cfg /Users/vsk/src/github-swift-master/build/Ninja-DebugAssert/lldb-macosx-x86_64/lit -sv
ninja: build stopped: subcommand failed.
./swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
```

2018-05-23 17:44 UTC, vedantk commented
@swift-ci test

2018-05-23 17:50 UTC, vedantk commented
I debugged a stale REPL session and found that the DataExtractor provided by the ValueObject for a simd vector actually contained the incorrect values. What's more, is that calling `print(vec)` also printed the wrong value for the vector.

I think this shows that the issue isn't a bug in the data formatter, but rather some kind of use-after-free or data corruption within a component which manages the REPL session's memory. I filed rdar://40490685 to track this.

I've kicked off a testing run because I'm curious about whether the test will fail on the bots.

2018-05-24 22:58 UTC, jimingham requested changes
The content of this looks fine.  And you were thorough in the tests, which is awesome (and caught the weird allocator bug!)

Your naming doesn't follow the rest of the lldb code.  We do:

UppercaseCamelCase

for all method names, not:

lowercaseCamelCase

For ivars we do:

m_varname

except for structs where you expect customers to directly access the ivar, in which case we do just:

varname

but that's fairly uncommon.  

local variables should be of the form:

word_word_word

Can you fix this, I don't want to start having the lldb code be incoherent in style.

Also, it would be nice to have a brief description of how you expect the data you are writing a summary for to be laid out.  That will help the next person who has to fix this when the format in the library changes.

2018-05-24 23:44 UTC, dcci approved these changes
The code looks fine to me (haven't paid lots of attention to style/conventions). Thanks!

2018-05-24 23:44 UTC, dcci commented
(meant to just comment, not approve, sorry).

2018-05-24 23:51 UTC, vedantk commented
@jimingham I've updated the coding style to be consistent with the rest of lldb, and added a comment about the data layout of simd vectors. PTAL.

2018-05-24 23:51 UTC, vedantk commented
@swift-ci test

2018-05-24 23:54 UTC, jimingham approved these changes
Looks great, thanks!

2018-05-25 00:04 UTC, vedantk commented
Thanks everyone! I'll see if I can get one more clean test run here to prep the commit. I'm working up a fix for the memory corruption bug in IRMemoryMap, and plan on landing that before this PR goes in.

2018-06-01 18:47 UTC, vedantk commented
This is superseded by #672.

2018-06-01 18:47 UTC, closed without merging